services:
  umbracalendar:
    container_name: umbracalendar-live
    image: ghcr.io/nul800sebastiaan/umbracalendar.site:latest
    ports:
      - "443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - data:/app/umbraco/Data
      - logs:/app/umbraco/Logs
      - media:/app/wwwroot/media
      - ./Hangfire.db:/app/Hangfire.db
      - ./appsettings.Production.json:/app/appsettings.Production.json

volumes:
  data:
  logs:
  media:
